import { lazy, type ComponentType, type LazyExoticComponent } from 'react'
import type { AppId } from '../os/types'

/** Every app is code-split so boot stays fast; apps load on first launch. */
export const APP_COMPONENTS: Record<AppId, LazyExoticComponent<ComponentType>> = {
  phone: lazy(() => import('./phone')),
  messages: lazy(() => import('./messages')),
  safari: lazy(() => import('./safari')),
  music: lazy(() => import('./music')),
  facetime: lazy(() => import('./facetime')),
  calendar: lazy(() => import('./calendar')),
  photos: lazy(() => import('./photos')),
  camera: lazy(() => import('./camera')),
  mail: lazy(() => import('./mail')),
  clock: lazy(() => import('./clock')),
  maps: lazy(() => import('./maps')),
  weather: lazy(() => import('./weather')),
  reminders: lazy(() => import('./reminders')),
  notes: lazy(() => import('./notes')),
  news: lazy(() => import('./news')),
  stocks: lazy(() => import('./stocks')),
  podcasts: lazy(() => import('./podcasts')),
  health: lazy(() => import('./health')),
  fitness: lazy(() => import('./fitness')),
  home: lazy(() => import('./home')),
  wallet: lazy(() => import('./wallet')),
  settings: lazy(() => import('./settings')),
  siri: lazy(() => import('./siri')),
  playground: lazy(() => import('./playground')),
  shortcuts: lazy(() => import('./shortcuts')),
  findmy: lazy(() => import('./findmy')),
  freeform: lazy(() => import('./freeform')),
  journal: lazy(() => import('./journal')),
  passwords: lazy(() => import('./passwords')),
  files: lazy(() => import('./files')),
  contacts: lazy(() => import('./contacts')),
  calculator: lazy(() => import('./calculator')),
  games: lazy(() => import('./games')),
  preview: lazy(() => import('./preview')),
  magnifier: lazy(() => import('./magnifier')),
}

/** Warm an app's chunk ahead of launch (e.g. on pointer down on its icon). */
export function preloadApp(app: AppId) {
  const loader = LOADERS[app]
  if (loader) void loader()
}

const LOADERS: Record<AppId, () => Promise<unknown>> = {
  phone: () => import('./phone'),
  messages: () => import('./messages'),
  safari: () => import('./safari'),
  music: () => import('./music'),
  facetime: () => import('./facetime'),
  calendar: () => import('./calendar'),
  photos: () => import('./photos'),
  camera: () => import('./camera'),
  mail: () => import('./mail'),
  clock: () => import('./clock'),
  maps: () => import('./maps'),
  weather: () => import('./weather'),
  reminders: () => import('./reminders'),
  notes: () => import('./notes'),
  news: () => import('./news'),
  stocks: () => import('./stocks'),
  podcasts: () => import('./podcasts'),
  health: () => import('./health'),
  fitness: () => import('./fitness'),
  home: () => import('./home'),
  wallet: () => import('./wallet'),
  settings: () => import('./settings'),
  siri: () => import('./siri'),
  playground: () => import('./playground'),
  shortcuts: () => import('./shortcuts'),
  findmy: () => import('./findmy'),
  freeform: () => import('./freeform'),
  journal: () => import('./journal'),
  passwords: () => import('./passwords'),
  files: () => import('./files'),
  contacts: () => import('./contacts'),
  calculator: () => import('./calculator'),
  games: () => import('./games'),
  preview: () => import('./preview'),
  magnifier: () => import('./magnifier'),
}
