/** Row-level search entries so Settings search finds individual switches, not just pages. */
export const EXTRA_INDEX: { title: string; route: string; keywords: string }[] = [
  { title: 'Airplane Mode', route: 'root', keywords: 'airplane flight offline' },
  { title: 'Connectivity Assist', route: 'cellular', keywords: 'handoff wifi cellular seamless drop' },
  { title: 'Wi‑Fi Quality Demo', route: 'cellular', keywords: 'wifi quality slider handoff' },
  { title: 'Data Roaming', route: 'cellular', keywords: 'roaming travel' },
  { title: 'Improved Bluetooth Power Management', route: 'bluetooth', keywords: 'bluetooth battery power' },
  { title: 'Low Power Mode', route: 'battery', keywords: 'battery saver low power' },
  { title: 'Battery Percentage', route: 'battery', keywords: 'percent status bar' },
  { title: 'Charge Limit', route: 'battery', keywords: 'charging optimized 80%' },
  { title: 'Dark Mode', route: 'appearance', keywords: 'appearance dark light theme night' },
  { title: 'Liquid Glass', route: 'appearance/glass', keywords: 'more clear more tinted transparency glass' },
  { title: 'Siri AI (Beta)', route: 'siri', keywords: 'siri ai beta waitlist' },
  { title: 'Brightness', route: 'display', keywords: 'screen brightness' },
  { title: 'True Tone', route: 'display', keywords: 'true tone color' },
  { title: 'Night Shift', route: 'display', keywords: 'warm color night' },
  { title: 'Accent Color', route: 'appearance/accent', keywords: 'tint color blue pink' },
  { title: 'Bold Text', route: 'accessibility/display', keywords: 'bold font weight' },
  { title: 'Larger Text', route: 'accessibility/textsize', keywords: 'text size dynamic type font' },
  { title: 'Increase Contrast', route: 'accessibility/display', keywords: 'contrast' },
  { title: 'Reduce Transparency', route: 'accessibility/display', keywords: 'transparency glass solid' },
  { title: 'Reduce Motion', route: 'accessibility/motion', keywords: 'motion animation' },
  { title: 'Icon Style', route: 'homescreen', keywords: 'dark tinted clear icons' },
  { title: 'Large Icons', route: 'homescreen', keywords: 'icon size' },
  { title: 'Silent Mode', route: 'sounds', keywords: 'mute ringer silent' },
  { title: 'Ringtone', route: 'sounds', keywords: 'ringtone reflection tone' },
  { title: 'Text Tone', route: 'sounds', keywords: 'message sound' },
  { title: 'Summarize Notifications', route: 'notifications', keywords: 'summary apple intelligence' },
  { title: '24-Hour Time', route: 'general/datetime', keywords: '24 hour military clock' },
  { title: 'Multilingual Typing', route: 'general/keyboard', keywords: 'languages keyboard bilingual' },
  { title: 'Check Spelling & Grammar', route: 'general/keyboard', keywords: 'grammar spelling' },
  { title: 'Auto-Punctuation', route: 'general/keyboard', keywords: 'dictation punctuation' },
  { title: 'Indigenous Language Keyboards', route: 'general/keyboard', keywords: 'cherokee hawaiian maori navajo inuktitut' },
  { title: 'English Variant', route: 'general/language', keywords: 'english uk india singapore ireland' },
  { title: 'AirDrop', route: 'general/airdrop', keywords: 'airdrop contacts everyone' },
  { title: 'Reset All Simulator Data', route: 'general/reset', keywords: 'erase reset factory' },
  { title: 'Custom EQ', route: 'airpods', keywords: 'equalizer bass treble vocal eq' },
  { title: 'Noise Cancellation', route: 'airpods', keywords: 'anc transparency adaptive' },
  { title: 'Heart Rate Sensing', route: 'airpods', keywords: 'heart rate fitness gymkit' },
  { title: 'Siri Voice', route: 'siri/voice', keywords: 'pace expressiveness voice' },
  { title: 'ChatGPT Extension', route: 'siri', keywords: 'chatgpt openai extension' },
  { title: 'Type to Siri', route: 'siri', keywords: 'type keyboard siri' },
  { title: 'Personal Context', route: 'siri', keywords: 'personal context onscreen awareness' },
  { title: 'Child Mode (Simulate Mia’s iPhone)', route: 'screentime/family', keywords: 'child mode simulate mia restrictions' },
  { title: 'Ask to Browse', route: 'screentime/browse', keywords: 'websites approve request' },
  { title: 'Time Allowances', route: 'screentime/allowances', keywords: 'allowance minutes games' },
  { title: 'Schedules', route: 'screentime/schedules', keywords: 'bedtime school hours' },
  { title: 'Communication Safety', route: 'screentime/safety', keywords: 'sensitive blur nudity' },
  { title: 'Recovery Contact', route: 'account/recovery', keywords: 'recovery contact code' },
  { title: 'Recovery Key', route: 'account/security', keywords: 'recovery key' },
  { title: 'iCloud Photos', route: 'account/icloud-photos', keywords: 'priority sync upload' },
  { title: 'Safety Check', route: 'privacy/safety-check', keywords: 'safety sharing emergency reset' },
  { title: 'Location Services', route: 'privacy', keywords: 'gps location' },
  { title: 'Default Card', route: 'wallet', keywords: 'apple pay default card' },
  { title: 'Car Key', route: 'wallet', keywords: 'car key proactive' },
  { title: 'Express Transit', route: 'wallet', keywords: 'transit card' },
  { title: 'Magnifier', route: 'accessibility', keywords: 'magnify zoom camera' },
  { title: 'Live Captions', route: 'accessibility', keywords: 'captions live' },
  { title: 'Caption Translation', route: 'accessibility/captions', keywords: 'translate subtitles' },
]
